### ISSUE TITLE
Explanation of Intertior Parameters 

### ISSUE THREAD

**Issue by geoeo** [3DOM-FBK/UseGeo#4]
Hello. Im not sure I understand the interior camera parameters?

`c        x0        y0        a3        a4        a5        a6      rho0`

Where c, x0 and y0 are the most important as the others are always 0.

c is the focal length in x and y?
x0 is the camera principal point in x
y0 is the camera princial point in y?

But then y0 is negative so that doesnt seem to make sense?

How would fov interior camera model look like with these parameters?

**Comment by geoeo** [comment]
Ok so I assume that the principal point y ist relative to the center of the image and not the top left corner

**Comment by 3DOM-FBK** [comment]
yes, the values are in pixels and the principal point has the origin in the image center (x horizontal and y vertical)

On 22 Jul 2024 at 09:38 +0200, 'Marc Haubenstock' via 3dom ***@***.***>, wrote:
> Ok so I assume that the principal point y ist relative to the center of the image and not the top left corner
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
--
Le informazioni contenute nella presente comunicazione sono di natura 
privata e come tali sono da considerarsi riservate ed indirizzate 
esclusivamente ai destinatari indicati e per le finalità strettamente 
legate al relativo contenuto. Se avete ricevuto questo messaggio per 
errore, vi preghiamo di eliminarlo e di inviare una comunicazione 
all’indirizzo e-mail del mittente.

--
The information transmitted is 
intended only for the person or entity to which it is addressed and may 
contain confidential and/or privileged material. If you received this in 
error, please contact the sender and delete the material.

**Comment by geoeo** [comment]
@3DOM-FBK 

I think there is a misunderstanding here / I am being slow. But the math doesn't check out on my end.

E.g. The first image in dataset 1 has size (with, height) = 7953, 5279. 
The interior parameters are c: 4636.912 x0: 3970.288 y0: -2601.560.

If x0 and y0 are w.r.t the image center then the values w.r.t. the top left corner are (w/2 + x0),  (h/2+y0)
In this case those value are 7940 and 38.5 which are unreasonable numbers for a principal point.

Is it possible that that x0 and y0 are w.r.t to an image corner afterall, but the sign in y is flipped?

In my experience its usually w.r.t the top left corner and the x0 and y0 are approx half of the width and height, but always positive. I couldnt find anything relating to the fov matrix of the camera in your paper so I have to ask here.

**Comment by 3DOM-FBK** [comment]
Hey Marc,

ok, we understood the issue:
the 0,0 of the principal point is in the upper left corner, so just ignore the “-“ in front of the yo value.
Therefore, the principal point is located at (3970.288, 2601.560).
Cheers,
Fabio

On 22 Jul 2024 at 15:01 +0200, 'Marc Haubenstock' via 3dom ***@***.***>, wrote:
> @3DOM-FBK
> I think there is a misunderstanding here / I am being slow. But the math doesn't check out on my end.
> E.g. The first image in dataset 1 has size (with, height) = 7953, 5279.
> The interior parameters are c: 4636.912 x0: 3970.288 y0: -2601.560.
> If x0 and y0 are w.r.t the image center then the values w.r.t. the top left corner are (w/2 + x0), (h/2+y0)
> In this case those value are 7940 and 38.5 which are unreasonable numbers for a principal point.
> Is it possible that that x0 and y0 are w.r.t to an image corner afterall, but the sign in y is flipped?
> In my experience its usually w.r.t the top left corner and the x0 and y0 are approx half of the width and height, but always positive. I couldnt find anything relating to the fov matrix of the camera in your paper so I have to ask here.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

-- 
--
Le informazioni contenute nella presente comunicazione sono di natura 
privata e come tali sono da considerarsi riservate ed indirizzate 
esclusivamente ai destinatari indicati e per le finalità strettamente 
legate al relativo contenuto. Se avete ricevuto questo messaggio per 
errore, vi preghiamo di eliminarlo e di inviare una comunicazione 
all’indirizzo e-mail del mittente.

--
The information transmitted is 
intended only for the person or entity to which it is addressed and may 
contain confidential and/or privileged material. If you received this in 
error, please contact the sender and delete the material.

**Comment by Vlyhhhhh** [comment]
Hello Geoeo,I am currently working with Dataset 1. However, I was unable to locate the information regarding the intrinsic parameters (c[px], x0[px], y0[px]) within the dataset.Could you kindly point me to where I might find these details?
