### ISSUE TITLE
Georeferenced Coordiante System

### ISSUE THREAD

**Issue by geoeo** [3DOM-FBK/UseGeo#5]
Hello,

I couldnt find anything on this topic. What is the coordiante system of the las file points you provide.
Somewhere in the VLR header I found a reference to EPSG:4258. Is this correct?

**Comment by 3DOM-FBK** [comment]
yes, it should be that one.
Best,
Fabio
On 17 Jul 2024 at 14:23 +0200, 'Marc Haubenstock' via 3dom ***@***.***>, wrote:
> Hello,
> I couldnt find anything on this topic. What is the coordiante system of the las file points you provide.
> Somewhere in the VLR header I found a reference to EPSG:4258. Is this correct?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
--
Le informazioni contenute nella presente comunicazione sono di natura 
privata e come tali sono da considerarsi riservate ed indirizzate 
esclusivamente ai destinatari indicati e per le finalità strettamente 
legate al relativo contenuto. Se avete ricevuto questo messaggio per 
errore, vi preghiamo di eliminarlo e di inviare una comunicazione 
all’indirizzo e-mail del mittente.

--
The information transmitted is 
intended only for the person or entity to which it is addressed and may 
contain confidential and/or privileged material. If you received this in 
error, please contact the sender and delete the material.
